language: rust
rust:
        - stable
matrix:
        allow_failure: 
                - rust : stable
cache:
    directories:
      - $HOME/.cargo/bin/
script :
        - ./install.sh
after_success: ""
env : RUSTFLAGS="$RUSTFLAGS -D warnings"
before_deploy:
        - npm install -g stylus nib
        - mdbook build
        - cp assets book/assets -R
        - touch book/.nojekyll
deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  
        keep-history: false  
        local-dir: book
        target-branch: gh-pages
        repo: ClubRobotInsat/doc
        project-name: Documentation Librobot
        on:
                branch: master
notifications:
          email: false
