language: rust
rust:
        - stable
matrix:
        allow_failure: 
                - rust : stable
cache : cargo
script : 
        - ./install.sh
after_success: ""
env : RUSTFLAGS="$RUSTFLAGS -D warnings"
before_deploy:
        - mdbook build
        - cp assets build/assets -R
deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  
        keep-history: false  
        local-dir: book
        target-branch: gh-pages
        repo: ClubRobotInsat/doc
        project-name: Documentation Librobot
        on:
                branch: master
notifications:
          email: false
