name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install MD book
      run: cargo install mdbook
    - name: clean
      run: mdbook clean
    - name: build page
      run: mdbook build
